/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/car6.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[34.56, 137.34, 11.04]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0.04, -0.07, 16.3]} rotation={[0, 0, -1.92]} />
          </group>
          <group position={[54.77, -2.07, -284.31]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0.01, 0.08, 199.33]} />
          </group>
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[40.51, 74.48, 0]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-43.61, 22.63, 55.69]}>
              <mesh geometry={nodes.car_body_body_0001_1.geometry} material={materials['body.001']} />
              <mesh geometry={nodes.car_body_body_0001_2.geometry} material={materials['glass.001']} />
              <mesh geometry={nodes.car_body_body_0001_3.geometry} material={materials['rubber.001']} />
              <mesh geometry={nodes.car_body_body_0001_4.geometry} material={materials['chest.001']} />
              <mesh geometry={nodes.car_body_body_0001_5.geometry} material={materials['interior.001']} />
              <mesh geometry={nodes.car_body_body_0001_6.geometry} material={materials['chrome.001']} />
              <mesh geometry={nodes.car_body_body_0001_7.geometry} material={materials['lights.001']} />
              <mesh geometry={nodes.car_body_body_0001_8.geometry} material={materials['number.001']} />
              <mesh geometry={nodes.car_body_body_0001_9.geometry} material={materials['wheels.001']} />
            </group>
          </group>
          <group position={[34.56, 137.34, 11.04]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0.04, -0.07, 16.3]} rotation={[0, 0, -1.92]} />
          </group>
          <group position={[54.77, -2.07, -284.31]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0.01, 0.08, 199.33]}>
              <group position={[0.24, -7.28, 149.23]} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/car6.glb')
